// <auto-generated />
using System;
using HrPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HrPlatform.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "0601234567",
                            DateOfBirth = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.petrovic@email.com",
                            Name = "Ana Petrović"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "0637654321",
                            DateOfBirth = new DateTime(1992, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko.nikolic@email.com",
                            Name = "Marko Nikolić"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "0651112233",
                            DateOfBirth = new DateTime(1998, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jelena.jovic@email.com",
                            Name = "Jelena Jović"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "0623334455",
                            DateOfBirth = new DateTime(1990, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "stefan.djordjevic@email.com",
                            Name = "Stefan Đorđević"
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "0615556677",
                            DateOfBirth = new DateTime(1997, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "milica.stojanovic@email.com",
                            Name = "Milica Stojanović"
                        });
                });

            modelBuilder.Entity("HrPlatform.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            SkillId = 1,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 3,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 1,
                            SkillId = 5,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 2,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 2,
                            SkillId = 3,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 1,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 4,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 3,
                            SkillId = 5,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 8,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 5,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 4,
                            SkillId = 6,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 5,
                            SkillId = 1,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 5,
                            SkillId = 4,
                            Id = 0
                        },
                        new
                        {
                            CandidateId = 5,
                            SkillId = 7,
                            Id = 0
                        });
                });

            modelBuilder.Entity("HrPlatform.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java Programming"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Database Design"
                        },
                        new
                        {
                            Id = 4,
                            Name = "React"
                        },
                        new
                        {
                            Id = 5,
                            Name = "English"
                        },
                        new
                        {
                            Id = 6,
                            Name = "German"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Project Management"
                        });
                });

            modelBuilder.Entity("HrPlatform.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("HrPlatform.Domain.Entities.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrPlatform.Domain.Entities.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HrPlatform.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("HrPlatform.Domain.Entities.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
